version: "3.9"

services:
  firstapp:
    build:
      context: ../dummy-app
      dockerfile: ./Dockerfile
      args:
        - JAVA_AGENT_VERSION=${JAVA_AGENT_VERSION}
    image: without-proxy-monitoring_firstapp_1
    ports:
      - "8091:8080"
    environment:
      - ELASTIC_APM_SERVICE_NAME=first-java-app
      - ELASTIC_APM_SERVER_URLS
      - ELASTIC_APM_SECRET_TOKEN
      - ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER=false
      - ELASTIC_APM_ENVIRONMENT=no-proxy
      - CONFIG_DOWNSTREAM_SERVICE_URL=nginx
  dummyapp:
    build:
      context: ../dummy-app
      dockerfile: ./Dockerfile
      args:
        - JAVA_AGENT_VERSION=${JAVA_AGENT_VERSION}
    image: without-proxy-monitoring_dummyapp_1
    ports:
      - "8092:8080"
    environment:
      - ELASTIC_APM_SERVICE_NAME=dummy-java-app
      - ELASTIC_APM_SERVER_URLS
      - ELASTIC_APM_SECRET_TOKEN
      - ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER=false
      - ELASTIC_APM_ENVIRONMENT=no-proxy
      - CONFIG_DOWNSTREAM_SERVICE_URL=nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: without-proxy-monitoring_nginx_1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "8082"
    ports:
      - "8082:80"
    depends_on:
      - apm-server

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.12.1
    ports:
      - "8200"
    volumes:
      - ./apm-server/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
