receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

  otlp:
    endpoint: apm-server:8200
    insecure: true

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        value: nginx-proxy
        action: insert
      - key: telemetry.sdk.name
        value: otel
        action: insert
      - key: telemetry.sdk.language
        value: nginx
        action: insert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging, otlp]